package constants

import java.lang.StringBuilder

/**
 * This class defines all constants of Loggerbird.
 */
internal class Constants {
    companion object {
        internal const val componentTag = "component"
        internal const val recyclerViewTag = "recyclerView"
        internal const val activityTag = "activity"
        internal const val lifeCycleTag = "life_cycle"
        internal const val fragmentTag = "fragment"
        internal const val analyticsTag = "analytics"
        internal const val fragmentManagerTag = "fragmentManager"
        internal const val fragmentLifeCycleObserverTag = "fragmentLifeCycleObserver"
        internal const val activityLifeCycleObserverTag = "activityLifeCycleObserver"
        internal const val httpTag = "http"
        internal const val okHttpTag = "okHttp"
        internal const val inAPurchaseTag = "in_a_purchase"
        internal const val retrofitTag = "retrofit"
        internal const val realmTag = "realm"
        internal const val exceptionTag = ""
        internal const val emailTag = "email"
        internal const val unHandledExceptionTag = "Unhandled Exception"
        internal const val logInitErrorMessage =
            "Call logInit method before calling any other method!"
        internal const val logInitAttachedErrorMessage =
            "logInit method is already attached to your application!"
        internal const val internetErrorMessage = "Invalid internet connection response code!"
        internal const val networkErrorMessage = "Invalid network response"
        internal const val SMTP_HOST_NAME: String = "smtp.gmail.com";
        internal const val exceedFileLimitTag: String = "Exceed File Limit"
        internal const val saveSessionOldFileTag: String = "Save Session Old File"
        internal const val workQueueUtilTag: String = "Work Queue Util"
        internal const val recyclerViewAdapterDataObserverTag: String =
            "RecyclerView Adapter Data Observer"
        internal const val recyclerViewChildAttachStateChangeListenerTag: String =
            "RecyclerView Child Attach State Change Listener"
        internal const val recyclerViewItemTouchListener: String =
            "RecyclerView Item Touch Listener"
        internal const val recyclerViewScrollListener: String = "RecyclerView Scroll Listener"
        internal const val serviceTag: String = "Service"
        internal const val performanceTag: String = "Performance"
        internal const val memoryUsageTag = "Memory Usage"
        internal const val memoryServiceTag = "Memory Service"
        internal const val cpuTag: String = "Cpu"
        internal const val screenShotTag: String = "Screenshot"
        internal const val floatingActionButtonTag: String = "Floating Action Button"
        internal const val floatingActionButtonOnTouchTag: String =
            "Floating Action Button On Touch"
        internal const val audioRecordingTag: String = "Audio Recording"
        internal const val audioStartRecordingTag: String = "Audio Start Recording"
        internal const val audioStopRecordingTag: String = "Audio Stop recording"
        internal const val videoRecordingTag: String = "Video Recording"
        internal const val videoRecordingSdkTag: String = "Call requires API level 21"
        internal const val foregroundServiceVideo: String = "Foreground Service Video"
        internal const val onActivityResultTag: String = "onActivityResult"
        internal const val onPermissionResultTag: String = "onPermissionResult"
        internal const val floatingActionButtonScreenshotTag: String =
            "Floating Action Button Screenshot"
        internal const val floatingActionButtonVideoTag: String = "Floating Action Button Video"
        internal const val floatingActionButtonAudioTag: String = "Floating Action Button Audio"
        internal const val paintViewTag: String = "Paint View"
        internal const val paintActivityTag: String = "Paint Activity"
        internal const val paintFabAnimationTag: String = "Paint Fab Animation"
        internal const val floatingActionButtonPaintTag: String = "Floating Action Button Paint"
        internal const val videoRecordingCounterTag: String = "Video Recording Counter"
        internal const val videoRecordingFileSizeTag: String = "Video Recording File Size"
        internal const val audioRecordingCounterTag: String = "Audio Recording Counter"
        internal const val audioRecordingFileSizeTag: String = "Audio Recording File Size"
        internal const val shakerTag: String = "Shake"
        internal const val feedbackTag: String = "Feedback"
        internal const val feedbackOnTouchTag: String = "Feedback On Touch"
        internal const val smartReplyFeedbackTag: String = "Smart Reply Feedback"
        internal const val translateTag: String = "Translator"
        internal const val translateDownloaderTag: String = "Translator Downloader"
        internal const val jiraAuthenticationtag: String = "Jira Authentication"
        internal const val checkboxRealmTag: String = "Checkbox Realm"
        internal const val actionFileTag: String = "Action File"
        internal const val singleFileDeleteTag: String = "Single File"
        internal const val discardFileTag: String = "Discard File"
        internal const val jiraTag: String = "Jira"
        internal const val recyclerViewJiraAdapterTag: String = "RecyclerView Jira Adapter"
        internal const val slackTag: String = "Slack Authorization"
        internal const val recyclerViewSlackAdapterTag: String = "RecyclerView Slack Adapter"
        internal const val loggerBirdToastTag: String = "LoggerBird Toast"
        internal const val unhandledExceptionPopupTag: String = "Unhandled Exception Popup"
        internal const val jiraDatePopupTag: String = "Jira Date Popup"
        internal const val futureTaskTag: String = "Future Task"
        internal const val githubTag: String = "Github"
        internal const val recyclerViewEmailAdapterTag: String = "RecyclerView Email Adapter"
        internal const val recyclerViewGithubAdapterTag: String = "RecyclerView Github Adapter"
        internal const val trelloTag: String = "Trello"
        internal const val recyclerViewTrelloAdapterTag: String = "RecyclerView Trello Adapter"
        internal const val gitlabTag: String = "GitLab"
        internal const val gitlabDatePopupTag: String = "Gitlab Date Popup"
        internal const val recyclerViewGitlabAdapterTag: String = "RecyclerView Gitlab Adapter"
        internal const val pivotalTag: String = "Pivotal"
        internal const val recyclerViewPivotalAdapterTag: String = "RecyclerView Pivotal Adapter"
        internal const val basecampTag: String = "Basecamp"
        internal const val recyclerViewBasecampAdapterTag: String = "RecyclerView Basecamp Adapter"
        internal const val asanaTag: String = "Asana"
        internal const val recyclerViewAsanaAdapterTag: String = "RecyclerView Asana Adapter"
        internal const val recyclerViewAsanaSubAdapterTag: String = "RecyclerView Asana Sub Adapter"
        internal const val recyclerViewClubhouseAdapterTag: String =
            "RecyclerView Clubhouse Adapter"
        internal const val clubhouseTag: String = "Clubhouse"
        internal const val clubhouseDatePopupTag = "Clubhouse Date Popup"
    }
}